#!/bin/sh

# Check whether GitHub CLI is installed
if ! command -v gh >/dev/null 2>&1; then
  echo "GitHub CLI (gh) is not installed. Please install it to proceed."
  exit 1
fi

# Check the result of "gh auth status"
gh auth status >/dev/null 2>&1
auth_status=$?

# login failed
if [ $auth_status -ne 0 ]; then
  echo "Logging in to GitHub..."
  gh auth login

  # Re-check auth status
  gh auth status >/dev/null 2>&1
  auth_status=$?
fi

# gh auth status succeeded
if [ $auth_status -eq 0 ]; then
  echo "Updating the GitHub secret with the contents of .env file..."
  cat .env
  gh secret set ENV_FILE_CONTENTS -b "$(cat .env)"
else
  echo "Failed to log in to GitHub. Please try again."
  exit 1
fi
